### ISSUE TITLE
Waiting for cert directory to get created...

### ISSUE THREAD

**Issue by gdschut** [marcoambrosini/aio-stalwart#8]
Sorry, I can't get it working. It keeps adding lines:
```
Waiting for cert directory to get created...
Waiting for cert directory to get created...
Waiting for cert directory to get created...
Waiting for cert directory to get created...
Waiting for cert directory to get created...
Waiting for cert directory to get created...
```
in the log
Im running behind a proxy (Traefik) so I choose "no" when configuring TLS certificates.
As I look into the container, and see start.sh is spitting this line out because it can not find the caddy files/folders

I also noted there is no logfile in `/opt/stalwart-mail/logs/*`, so I cannot find the password generated...
What am I doing wrong?

**Comment by ArmedSnail** [comment]
same here, I am using a distinct nginx container instead of the built-in caddy from nextcloud-aio.
Container hangs on said error message and logs are not populated with a password.

**Comment by quetzalism** [comment]
I'm in the same boat. 

Use: 
C:\WINDOWS\system32>docker exec -it nextcloud-aio-stalwart configure.sh

Welcome to the Stalwart Mail Server installer

✔ Which database would you like to use? · RocksDB (recommended for single-node setups)
✔ Where would you like to store e-mails and other large binaries? · Local file system
✔ Where would you like to store the full-text index? · RocksDB
✔ Where would you like to store the anti-spam database? · RocksDB
✔ Do you already have a directory or database containing your user accounts? · No, I want Stalwart to store my user accounts in RocksDB
✔ What is your main domain name? (you can add others later) · redacted.domain.tld
✔ What is your server hostname? · mail.redacted.domain.tld
Do you want the TLS certificates for mail.redacted.domain.tld to be obtained automatically from Let's Encrypt using ACME? yes

🛡️ Ensure that port 443 (HTTPS) on mail.redacted.domain is open and accessible from the internet to successfully obtain your ACME TLS certificate.

🔑 The administrator account is 'admin' and the password can be found in the log files at /opt/stalwart-mail/logs.

✅ Add the following DNS records to your domain in order to enable DKIM, SPF and DMARC:

------

There are no logs in the Docker Container When (using docker for desktop on my windows 10 machine) Navigating to Volumes > nextcloud_aio_stalwart > logs | so I can't find this alleged password.

------
When i navigate to Docker Desktop Containers > Logs, I just see 
`2024-03-22 18:31:00 Waiting for cert directory to get created...`
repeated every second over and over until i stop the container. 

------

I am using cloudflared tunnels set where nc.domain.tld is my working nextcloud install and mail.nc.domain.tld is set to https://localhost:443

Please help me I'm very new to self hosting

**Comment by kri164** [comment]
This container is functional with nextcloud-caddy container only.
Startup script waits for caddy to make/renew certificates. Without this it will not start.
So no logs are written.
You can try luck with offcial containers from Stalwart Labs.

**Comment by docjyJ** [comment]
Fix
